# Generated by Django 5.1.4 on 2025-01-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=100)),
                ('user_img', models.ImageField(upload_to='user_images')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_city', models.CharField(max_length=50)),
                ('user_phone_no', models.IntegerField()),
                ('user_zip_code', models.IntegerField()),
            ],
        ),
    ]
